jobs:
  synchronize-with-crowdin:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      env:
        CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      name: crowdin action
      uses: crowdin/github-action@master
      with:
        config: crowdin.yml
        crowdin_branch_name: master
        download_translations: false
        upload_sources: true
        upload_translations: false
name: Crowdin Action
on:
  repository_dispatch:
    types: trigger-ga___crowdin.yml
